document.writeln("<div id=\"ffgg\" style=\"margin: auto;left:0; right:0;bottom:0;position:fixed;text-align:center;z-index:99999;background:#000;filter:alpha(opacity=80);-moz-opacity:0.8;-khtml-opacity:0.8;opacity:0.8;\">");
document.writeln("<a href=\"https://down-1257840286.cos.ap-guangzhou.myqcloud.com/huorong.rar\" target=\"_blank\"><img src=\"images/huorong.png\">  ");
document.writeln("<p onclick=\"removeElement(\'ffgg\')\" ><a style=\"display: block;");
document.writeln("    position: fixed;");
document.writeln("    width: 53px;");
document.writeln("    height: 52px;");
document.writeln("    -webkit-transition: all 400ms;");
document.writeln("    z-index: 10000;");
document.writeln("    right: 50px;");
document.writeln("    bottom: 20px;\"></a></p> ");
document.writeln("  ");
document.writeln("</div>");
document.writeln("<script type=\"text/javascript\">");
document.writeln("function removeElement(ffgg)");
document.writeln("{");
document.writeln("document.getElementById(ffgg).style.display=\"none\";");
document.writeln("}");
document.writeln("</script>");